jobs:
  build:
    steps:
    - run:
        command: |
          nix-channel --add https://nixos.org/channels/nixos-19.03 nixpkgs
          nix-channel --update
        name: Update nixos-19.03
    - run:
        command: |
          mkdir -p ~/.config/nixpkgs
          echo "{allowUnfree = true;}" >> ~/.config/nixpkgs/config.nix
        name: Forfeit freedom
    - run:
        command: |
          nix-env -u
          nix-env -i coreutils openssh git bash cachix
        name: Install Utils
    - checkout
    - run:
        command: |
          mkdir -p /etc/nix
          echo "build-cores = 2" >> /etc/nix/nix.conf
        name: Configure Nix
    - run:
        command: |
          cachix use rdf
        name: Setup Cachix
    - run:
        command: |
          nix-shell --pure --run "cabal new-update && cabal new-build -j$(nproc)"
        name: Build rdf
    docker:
    - image: nixos/nix:2.2.1
version: 2
workflow:
  version: 2
  build-and-test:
    jobs:
    - build
